### ISSUE TITLE
Geometry dash broken trail

### ISSUE THREAD

**Issue by lapislazulii1** [maxnut/GDMegaOverlay#107]
When I play a level on geometry dash the trail when you click on orbs is broken and laggy and weird, I'm not sure if it because if mega overlay or if it's just gd being broken but can someone help me fix this or give any advice that would be very helpful thank you!

**Comment by Gavin-TC** [comment]
have you tried turning off all hacks to maybe narrow it down to a specific one?

**Comment by lapislazulii1** [comment]
Yes I have but it still is broken
