### ISSUE TITLE
GDMO Macro issue

### ISSUE THREAD

**Issue by Koyomi-0** [maxnut/GDMegaOverlay#126]
Any Macro file that ends in `.Macro` just kind of crashes the entire game on a runtime error

Reproduceable by entering name of macro within the macro Load / Save textbox and entering Load

**Comment by maxnut** [comment]
what macro u loading
old macros dont work

**Comment by Koyomi-0** [comment]
Well I was loading old ones, expected them to be the same files read but in assuming it's diff mb
