### ISSUE TITLE
Plz Make Macro bot accurate

### ISSUE THREAD

**Issue by LousyBook05** [maxnut/GDMegaOverlay#152]
There is a bug in your marco bot that makes it when you teleport the macro becomes inaccurate the only way to fix it is to stop holding and hold again in platformer mode.
also still inaccurate for both modes

PLZZ ADD INTERNAL RECORDER AND SHOW HITBOX AND TRAJECTORY TOO

**Comment by maxnut** [comment]
what

**Comment by Stronkkey** [comment]
"When the player teleports, the macro breaks, you can fix this by pressing the mouse." The implication here is that the macrobot should not break (it was and is still shit for a couple of reasons) when you teleport, but it does break.

**Comment by maxnut** [comment]
hey calling it shit is not nice it improved a lot

**Comment by Stronkkey** [comment]
I mean it's not bad. But it's really rough around the edges (talking about the 2.1 bot).

**Comment by maxnut** [comment]
2.1 by gd version or gdmo? current bot is definitely better than old gdmo without corrections, old bot was kinda shit without them

**Comment by Stronkkey** [comment]
Wdym "without corrections"? It works even without corrections and pretty nicely if you are careful (don't do anything funky on slopes, lookout for rotation bug, don't instantly press after respawning). Also I am talking about v2.1.
