### ISSUE TITLE
Feature Requests and other things

### ISSUE THREAD

**Issue by LousyBook05** [maxnut/GDMegaOverlay#164]
Add Internal Recorder and Selector for Macros , And Disable Shaders options Plz  and Also Macrobot doesn't run in realtime when there are shaders or too many actions, this might be a issue bcuz my graphics card sucks, could you try skipping frames or something and also Macrobot freezes in place without the fps toggle on in your menu and also macrobot doesn't run in real time in high fps

**Comment by ImaDoor2785** [comment]
all of the macro issues you described are just because your computer is too weak, and frame skipping "if its even possible" would make most levels impossible to accurately record especially the ship
disable shader option is actually a good idea

**Comment by maxnut** [comment]
how many times do i have to say this is not a place for suggestions. join the discord

**Comment by LousyBook05** [comment]
@ImaDoor2785  Yes, Mr Door
