### ISSUE TITLE
Cross-platform support

### ISSUE THREAD

**Issue by SpektacleFR** [maxnut/GDMegaOverlay#19]
Although a big ask, is it possible to see this compatible for the macOS version of GD in the future?  I personally am not sure what mod development on macOS looks like, or if it's drastically different from Windows, but would gd.h even be compatible with macOS?  Thanks.

**Comment by SpaghettDev** [comment]
The addresses would for sure have to change.
Other than that, i think some proprietary windows functions will change and that's pretty much it i beleive...

**Comment by iAndyHD3** [comment]
For mac, install geode and use [Crystal Client](https://github.com/ninXout/Crystal-Client). Its pretty much impossible to target other platform with current code
