### ISSUE TITLE
Mod Loader For Other Game Interferes With Geode

### ISSUE THREAD

**Issue by FistInYourSister** [maxnut/GDMegaOverlay#215]
I cant download geode because Xinput1_3.dll is interfering with geode, when trying to install geode it says i have to delete Xinput as geode wont run with any other "mod loaders", i have Xinput downloaded for Palworld mods and my controller needs it for DS4windows to run properly... i am fully unable to use your menu without deleting this

**Comment by MysticAx0lotl** [comment]
This sounds like an issue with the Geode launcher, you may want to open an issue there. Before you do that, are you sure the installer is pointed to the right folder?

**Comment by maxnut** [comment]
you need to delete it from the gd folder. also how is this a gdmo issue??
