### ISSUE TITLE
Change splash text

### ISSUE THREAD

**Issue by SpyderThingy** [maxnut/GDMegaOverlay#33]
Is it possible to create a splash text customiser?
Also btw the labels on the side keep freezing in the new update :/

**Comment by SpektacleFR** [comment]
Splash text as in the "Geometry Dash" title screen, or the "Tip: Don't Crash" stuff while the game is loading the textures etc.?

If it's the former, this can only be done by modifying the texture pack directly, as the Geometry Dash title screen is stored there.  If you're talking about the goofy text on load, I'm not exactly sure how this is implemented, so I don't have input on that.

**Comment by MeoNguOfficial** [comment]
You can provide more image to view problem

**Comment by SpyderThingy** [comment]
> Splash text as in the "Geometry Dash" title screen, or the "Tip: Don't Crash" stuff while the game is loading the textures etc.?
> 
> If it's the former, this can only be done by modifying the texture pack directly, as the Geometry Dash title screen is stored there. If you're talking about the goofy text on load, I'm not exactly sure how this is implemented, so I don't have input on that.

The Tip: Don't crash stuff

**Comment by SpaghettDev** [comment]
> > Splash text as in the "Geometry Dash" title screen, or the "Tip: Don't Crash" stuff while the game is loading the textures etc.?
> > 
> > If it's the former, this can only be done by modifying the texture pack directly, as the Geometry Dash title screen is stored there. If you're talking about the goofy text on load, I'm not exactly sure how this is implemented, so I don't have input on that.
> 
> The Tip: Don't crash stuff

You can fork this repo and modify the MenuLayer.cpp file to have whatever you want appear in the splash screen.

**Comment by SpyderThingy** [comment]
Thx
