### ISSUE TITLE
Auto-Updates and an Internet Connection

### ISSUE THREAD

**Issue by LowoTV** [maxnut/GDMegaOverlay#40]
Whenever the game tries to auto-update, it checks whether it can update or not, and that is fine, my problem is when the internet is out, eg. No Electricity. The game crashes, a fix is that the game could check for internet, and if the isn't any, it should stop attempting to auto-update, or idk, maybe that's what it's doing

**Comment by SpektacleFR** [comment]
I we're brainstorming for updater fixes, I propose this idea:
 * Try connecting to the update server (basically just ping it)
 * IF a response is received, update as per normal operation
 * ELSE, send an error code and in-UI popup stating the error code.

This should all be Async, of course.  This way, we wouldn't have to check if there is an active Wi-Fi connection, and this can also catch if the update server is down.  It also wouldn't require the use of the Win32 API to check if there is an active Wi-Fi connection on the system.  I assume it would also be easier to implement.

I've gotten a bit ahead of myself.  Were there any logs output by the mod?  If so, please supply those as well :)

**Comment by LowoTV** [comment]
> I we're brainstorming for updater fixes, I propose this idea:
> 
> * Try connecting to the update server (basically just ping it)
> * IF a response is received, update as per normal operation
> * ELSE, send an error code and in-UI popup stating the error code.
> 
> This should all be Async, of course. This way, we wouldn't have to check if there is an active Wi-Fi connection, and this can also catch if the update server is down. It also wouldn't require the use of the Win32 API to check if there is an active Wi-Fi connection on the system. I assume it would also be easier to implement.
> 
> I've gotten a bit ahead of myself. Were there any logs output by the mod? If so, please supply those as well :)

How do I look for the log file?

**Comment by LowoTV** [comment]
woops

**Comment by CoolingJam** [comment]
Fixed in pull request #55
