### ISSUE TITLE
Standalone clickbot and recorder

### ISSUE THREAD

**Issue by MrNooberDude** [maxnut/GDMegaOverlay#43]
So, I've been interested in this for it's clickbot capabilities, however, as a megahack user, it would be really nice to have a standalone clickbot and macro recorder for download that has MHv7 support. Hopefully you could do this, or provide instructions for building the current code with the standalone stuff mentioned.

**Comment by greenmovie13** [comment]
should be put in the discussions tab rather than under issues

**Comment by MrNooberDude** [comment]
Alright, good to know! Still learning, relatively new to this stuff.
