### ISSUE TITLE
Not completing level

### ISSUE THREAD

**Issue by AvgGd** [maxnut/GDMegaOverlay#47]
I don't have uncomplete level on, I have safemode off, i have everything off and I play a level, I beat it and it only stores the regular.
If I die at 89% and then next attempt complete it, it will stay at 89%.
It's weird and I don't know how to describe it

**Comment by CoolingJam** [comment]
Same

**Comment by AvgGd** [comment]
Will this ever be fixed?

**Comment by konto69** [comment]
disable "force safe mode" and then "safe mode" (in order)
