### ISSUE TITLE
Opening the community shop crashes the game

### ISSUE THREAD

**Issue by OofLmao** [maxnut/GDMegaOverlay#56]
As said in the title, opening the community shop in the chest room crashes the game. I can't test if opening Scratch's shop yields the same results.

**Comment by iambeingtracked** [comment]
Happens to me too


And opening the Scratch's shop does the same

**Comment by evergreenvr** [comment]
i had to uninstall it for me to open the community shop

**Comment by evergreenvr** [comment]
you need to uninstall mega overlay then go into the community shop and scratches shop then quit the game and reinstall it then launch gd from the .exe

**Comment by iambeingtracked** [comment]
seems like it was fixed with the new update
