### ISSUE TITLE
how to open clickgui

### ISSUE THREAD

**Issue by Mrsundayzz** [maxnut/GDMegaOverlay#68]
**Do not send an issue about bugs in the menu itself. They will simply be ignored. The place to submit bugs is the discord server**
how do i open the click gui?

**Comment by maxnut** [comment]
what. this is not an issue

**Comment by Malte0621** [comment]
What's the keybind to open it? X_X
The github repo doesn't have any instructions or information about it..

**Comment by Malte0621** [comment]
after wasting quite some time trying to find the shortcut in this repository's code without any success. I opened GD with it installed and managed to open the menu using the TAB key after smashing my keyboard's every key.
