### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by TechStudent10** [maxnut/GDMegaOverlay#71]
Here are some bugs I've found while using the menu:
1. If you have default mini-icon, sometimes it does not, especially in practice mode. Tends to be random
2. No wave pulse despite having the mod off
3. While recording a macro using the macro bot, the game crashes on holding on a dash orb
4. Levels not completing despite safe mode off (#47)

**Comment by TechStudent10** [comment]
For 2. set wave pulse to 2.1

For 4. turn safe mode on and off as a workaround

**Comment by maxnut** [comment]
3 has been fixed for awhile now, it was due to trajectory
1 i have no idea what youre talking about

**Comment by TechStudent10** [comment]
> 3 has been fixed for awhile now, it was due to trajectory

You have to turn off trajectory for it to work or was it fixed? If it's the former then that's more of a workaround than a fix

> 1 i have no idea what youre talking about

In the GD settings there is an option called "Default Mini Icon" that, as the name suggests, changes the icons of both the mini cube and mini ball to the "default". GDMO bugs out and sometimes acts as if the option was never enabled. Usually happens while respawning in practice mode but I've also found that if you're a mini cube then enter a cube portal it again bugs out as described here. Keep in mind this also happens with the ship and UFO as they use the cube as part of their icons.
