### ISSUE TITLE
Endscreen pause allows you to complete levels

### ISSUE THREAD

**Issue by iambeingtracked** [maxnut/GDMegaOverlay#80]
Kind of hard to describe but here's a video https://files.wherelinux.xyz/gd-bug.mkv

Basically to reproduce
1. start playing a level
2. enter practice mode
3. wait till your icon gets into the level end wall
4. pause
5. quit practice mode
6. level gets completed and you get 100% on it in normal mode

I accidentally completed a demon like that (oops)

edit: that's just a random level I found to demonstrate

**Comment by maxnut** [comment]
#82

**Comment by iambeingtracked** [comment]
Is it possible to fix without making it a cheat?
