### ISSUE TITLE
Progress bar is over 100,00%

### ISSUE THREAD

**Issue by MeoNguOfficial** [maxnut/GDMegaOverlay#87]
Can you fix it?

**Comment by maxnut** [comment]
what

**Comment by MeoNguOfficial** [comment]
Like this
![image](https://github.com/maxnut/GDMegaOverlay/assets/135810477/6ffe0707-997e-47d2-9f03-4d3e1c0a82c8)

**Comment by maxnut** [comment]
if you have accurate percentage thats just what it does

**Comment by MeoNguOfficial** [comment]
i know but i think many people don't like this
